<!DOCTYPE html>
<html>
	<head>
		<title><?php echo isset($pageTitle) ? $pageTitle : "PHP Code Sample -- I hope you like it!" ?></title>
		<?php 
			if(isset($aJS)){
				foreach($aJS as $js){
					echo "<script type=\"text/javascript\" src=\"$js\"></script>\n";
				}
			}
			if(isset($aCSS)){
				foreach($aCSS as $css){
					echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"$css\">\n";
				}
			}
		?>
	</head>
	<body>